---
# tasks file for tmux
# - name: Get current tmux version
#   command: tmux -V
#   register: tmux_current_version
#   changed_when: False
#
# - name: Set flag to true if upgrade needed
#   set_fact:
#     tmux_upgrade: "{{ tmux_current_version.stdout.split(' ')[1] is version(tmux_version, '<') }}"
#
# - name: Install tmux from source
#   include_tasks: build2.yml
#
# - debug:
#     msg: "Tmux needs to be upgraded!"
#   when: tmux_upgrade

- name: Install tmux
  include_tasks: "{{ ansible_facts['os_family'] }}.yml"
  when: ansible_facts['os_family'] not in tmux_build_from_source

- name: Install tmux from source
  include_tasks: build.yml
  when: ansible_facts['os_family'] in tmux_build_from_source
