---
- name: Rust | Install
  shell: "curl https://sh.rustup.rs -sSf | sh -s -- -y"
  changed_when: false

- name: Rust | Install toolchain
  command: "{{ rust_user_dir }}/.cargo/bin/rustup toolchain install {{ item }}"
  register: rustup_toolchain_install
  changed_when: "'installed' in rustup_toolchain_install.stdout"
  loop: "{{ rust_toolchains }}"
  when: item is defined
