---
# tasks for dotfiles
- name: Clone dotfiles repo
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_dest }}"
    version: HEAD
    key_file: "{{ ansible_env.HOME }}/.ssh/id_rsa"
    accept_hostkey: true
    force: false
    update: true

- name: Run dotdrop install
  command: "{{ dotdrop_bin }} install -c {{ dotdrop_cfg }} --force"
  register: dotinstall
  changed_when: "'0 dotfile(s) installed' not in dotinstall.stdout"
