---
# tmux
- name: Clone tmux master
  git:
    repo: https://github.com/tmux/tmux
    dest: "{{ tmux_source_dir }}"
    depth: "1"
    force: true
  register: tmux_git_clone

- name: Debug changes to git
  debug:
    msg: |
      Before:      {{ tmux_git_clone.before }}
      After:       {{ tmux_git_clone.after }}
      Force build: {{ tmux_force_build }}
    verbosity: 1

- name: Build tmux and deps from source if changes
  block:
    - name: Check libevent exists
      stat:
        path: "{{ tmux_libevent_path }}"
      register: tmux_libevent_stat

    - name: Check ncurses exists
      stat:
        path: "{{ tmux_ncurses_path }}"
      register: tmux_ncurses_stat

    - name: Download and build libevent
      block:
        - name: Download libevent
          unarchive:
            src: "https://github.com/libevent/libevent/releases/download/release-{{ tmux_libevent_version }}\
            -stable/libevent-{{ tmux_libevent_version }}-stable.tar.gz"
            dest: "{{ tmux_source_dir }}"
            remote_src: true

        - name: Build libevent
          command: "{{ item }}"
          args:
            chdir: "{{ tmux_libevent_path }}"
          loop:
            - ./configure --prefix={{ tmux_install_prefix }}
            - make -j{{ tmux_make_concurrency }}
            - make install
      when: tmux_libevent_stat.stat.isdir is not defined

    - name: Download and build ncurses
      block:
        - name: Download ncurses
          unarchive:
            src:
              https://ftp.gnu.org/pub/gnu/ncurses/ncurses-{{ tmux_ncurses_version }}.tar.gz
            dest: "{{ tmux_source_dir }}"
            remote_src: true

        - name: Build ncurses
          command: "{{ item }}"
          args:
            chdir: "{{ tmux_ncurses_path }}"
          loop:
            - ./configure --prefix={{ tmux_install_prefix }}
            - make -j{{ tmux_make_concurrency }}
            - make install
      when: tmux_ncurses_stat.stat.isdir is not defined

    - name: Build and install tmux
      command:
        cmd: "{{ item }}"
        chdir: "{{ tmux_source_dir }}"
      loop:
        - sh autogen.sh
        - >-
          ./configure --prefix={{ tmux_install_prefix }}
            CPPFLAGS="-I{{ tmux_install_prefix }}/include -I{{ tmux_install_prefix }}/include/ncurses"
            LDFLAGS="-L{{ tmux_install_prefix }}/lib"
        - make -j{{ tmux_make_concurrency }}
        - make install
  when: (tmux_git_clone.before != tmux_git_clone.after) or tmux_force_build
