---
# tasks file for tmux
- name: tmux | Build and install from source
  import_tasks: build.yml
  when: ansible_facts['os_family'] in tmux_build_from_source

- name: tmux | Install using package manager
  include_tasks: "{{ ansible_facts['os_family'] }}.yml"
  when: ansible_facts['os_family'] not in tmux_build_from_source
