---
# arch
- name: Install development packages for building asdf/python
  apt:
    update_cache: true
    cache_valid_time: "{{ 48 * 60 * 60 }}"  # consider cache valid within 48 hours
    pkg: "{{ asdf_debian_packages }}"
    state: present
  become: true
