---
# asdf plugins
- name: asdf | Install asdf plugins
  command: "{{ asdf_bin }} plugin-add {{ item.name }} {{ item.repository|d() }}"
  args:
    creates: "{{ asdf_dir }}/plugins/{{ item.name }}"
    chdir: "{{ asdf_home }}"
  loop: "{{ asdf_plugins|flatten(levels=1) }}"

# Plugin-specific tasks go here
- name: asdf | Include tasks for nodejs
  include_tasks: plugins/nodejs.yml
  loop: "{{ asdf_plugins|flatten(levels=1) }}"
  when: '"nodejs" in item["name"]'

- name: asdf | Include tasks for python
  include_tasks: plugins/python.yml
  loop: "{{ asdf_plugins|flatten(levels=1) }}"
  when: '"python" in item["name"]'

# Install binaries using plugins
- name: asdf | Install asdf packages
  command: "{{ asdf_bin }} install {{ item.0.name }} {{ item.1 }}"
  args:
    creates: "{{ asdf_dir }}/installs/{{ item.0.name }}/{{ item.1 }}"
    chdir: "{{ asdf_home }}"
  environment: "{{ item.0.environment|d({}) }}"
  loop: "{{ asdf_plugins|subelements('versions', {'skip_missing': True}) }}"

- name: asdf | Set global asdf package versions
  command: "{{ asdf_bin }} global {{ item.name }} {{ item.global| d(item.versions[0]) }}"
  args:
    chdir: "{{ asdf_home }}"
  loop: "{{ asdf_plugins|flatten(levels=1) }}"
  when: item.versions is defined
  changed_when: false
