---
# asdf shell tasks
- name: Check whether fish completion dir exists
  stat:
    path: "{{ asdf_fish_config_dir }}"
  register: asdf_fish_config_dir_st

- name: Check whether asdf.fish file exists
  stat:
    path: "{{ asdf_dir }}/completions/asdf.fish"
  register: asdf_fish_completions_st

- name: Copy fish completions
  copy:
    src: "{{ asdf_dir }}/completions/asdf.fish"
    dest: "{{ asdf_home }}/.config/fish/completions/asdf.fish"
    remote_src: true
  when:
    - asdf_fish_config_dir_st.stat.exists
    - asdf_fish_completions_st.stat.exists
