---
cmdargs:
  verbose: false
  severity: style_problem
  error-limit: 50
  stat: false
  color: false
  json: false
  env:
    neovim: true
  stdin_display_name: stdin

policies:
  # Experimental
  ProhibitUnusedVariable:
    enabled: false
  ProhibitUsingUndeclaredVariable:
    enabled: true
  ProhibitImplicitScopeVariable:
    enabled: true
  ProhibitNoAbortFunction:
    enabled: false
# ProhibitSetNoCompatible:
#   enabled: false
