actions:
  pre:
    vim-plug-install: test -e ~/.vim/autoload/plug.vim || (mkdir -p ~/.vim/autoload;
      curl -fLo ~/.vim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim)
  vim-plug: vimsync
config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: true
  link_by_default: true
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  d_after:
    dst: ~/.vim/after
    link: true
    src: .vim/after
  d_autoload:
    dst: ~/.vim/autoload
    link: true
    src: .vim/autoload
  d_bash:
    dst: ~/.config/bash
    link: true
    src: .config/bash
  d_config:
    dst: ~/.vim/config
    link: true
    src: .vim/config
  d_fish:
    dst: ~/.config/fish
    link: true
    src: .config/fish
  d_ftdetect:
    dst: ~/.vim/ftdetect
    link: true
    src: .vim/ftdetect
  d_ftplugin:
    dst: ~/.vim/ftplugin
    link: true
    src: .vim/ftplugin
  d_nvim:
    dst: ~/.config/nvim
    link: true
    src: .config/nvim
  d_omf:
    dst: ~/.config/omf
    link: true
    src: .config/omf
  d_powerline:
    dst: ~/.config/powerline
    link: true
    src: .config/powerline
  d_topydo:
    dst: ~/.config/topydo
    link: true
    src: .config/topydo
  d_xonsh:
    dst: ~/.config/xonsh
    link: true
    src: .config/xonsh
  d_zsh:
    dst: ~/.config/zsh
    link: true
    src: .config/zsh
  f_bash_aliases:
    dst: ~/.bash_aliases
    link: true
    src: bash_aliases.sh
  f_bash_colors:
    dst: ~/.bash_colors
    link: true
    src: bash_colors.sh
  f_bash_functions:
    dst: ~/.bash_functions
    link: true
    src: bash_functions.sh
  f_bash_linux:
    dst: ~/.bash_linux
    link: true
    src: bash_linux.sh
  f_bash_mac:
    dst: ~/.bash_mac
    link: true
    src: bash_mac.sh
  f_bash_profile:
    dst: ~/.bash_profile
    link: true
    src: bash_profile.sh
  f_bash_prompt:
    dst: ~/.bash_prompt
    link: true
    src: bash_prompt.sh
  f_bash_windows:
    dst: ~/.bash_windows
    link: true
    src: bash_windows.sh
  f_bashrc:
    dst: ~/.bashrc
    link: true
    src: bashrc.sh
  f_dircolors:
    dst: ~/.dircolors
    link: true
    src: dircolors.sh
  f_tmux.conf:
    dst: ~/.tmux.conf
    link: true
    src: tmux.conf
  f_tmux.theme.conf:
    dst: ~/.tmux.theme.conf
    link: true
    src: tmux.theme.conf
  f_vimrc:
    actions:
    - vim-plug-install
    - vim-plug
    dst: ~/.vimrc
    link: true
    src: vimrc.vim
  f_xonshrc:
    dst: ~/.xonshrc_orig
    link: true
    src: xonshrc.py
  f_zshrc:
    dst: ~/.zshrc
    link: true
    src: zshrc.zsh
profiles:
  core:
    dotfiles:
    - f_bashrc
    - f_bash_colors
    - f_bash_prompt
    - f_bash_profile
    - f_bash_aliases
    - f_bash_functions
    - f_dircolors
    - f_tmux.conf
    - f_tmux.theme.conf
    - f_vimrc
    - f_xonshrc
    - f_zshrc
    - d_after
    - d_autoload
    - d_config
    - d_bash
    - d_fish
    - d_ftplugin
    - d_ftdetect
    - d_nvim
    - d_powerline
    - d_topydo
    - d_xonsh
    - d_zsh
  io:
    dotfiles:
    - f_bash_linux
    - f_bash_windows
    include:
    - core
  joppa:
    dotfiles:
    - f_bash_linux
    include:
    - core
  thor.local:
    dotfiles:
    - f_bash_mac
    include:
    - core
  uranus:
    dotfiles:
    - f_bash_windows
    include:
    - core
