config:
  backup: true
  banner: false
  create: true
  dotpath: ~/dotfiles
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: link
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  d_config:
    dst: ~/.config
    link: link_children
    src: .config
  d_mutt:
    dst: ~/.mutt
    link: link
    src: .mutt
  f_bash_profile:
    dst: ~/.bash_profile
    link: link
    src: bash_profile.sh
  f_bashrc:
    dst: ~/.bashrc
    link: link
    src: bashrc.sh
  f_muttrc:
    dst: ~/.muttrc
    link: link
    src: muttrc
  f_xonshrc:
    dst: ~/.xonshrc_orig
    link: link
    src: xonshrc.py
  f_zshrc:
    dst: ~/.zshrc
    link: link
    src: zshrc.zsh
  d_ansible:
    src: .ansible
    dst: ~/.ansible
    link: link
  f_ignore:
    src: .ignore
    dst: ~/.ignore
    link: link
  d_bin:
    src: bin
    dst: ~/bin
    link: link
  f_vintrc.yaml:
    src: vintrc.yaml
    dst: ~/.vintrc.yaml
    link: link
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
    link: link
  f_ugrep:
    src: ugrep
    dst: ~/.ugrep
    link: link
profiles:
  core:
    dotfiles:
    - f_bashrc
    - f_bash_profile
    - f_xonshrc
    - f_zshrc
    - d_config
    - f_ignore
    - d_bin
    - f_vintrc.yaml
    - f_vimrc
    - f_ugrep
  io:
    include:
    - core
  jupiter:
    dotfiles:
    - d_mutt
    - f_muttrc
    include:
    - core
    - ansible
  mars:
    include:
    - core
  thor.local:
    include:
    - core
  titan:
    include:
    - core
  ansible:
    dotfiles:
    - d_ansible
trans_read:
  gpg: gpg2 -d -o {1} -r nick {0}
trans_write:
  gpg: gpg2 -e -o {1} -r nick {0}
