---
# tasks for arch hosts
- name: Create aur module user
  block:
    - name: Create user aur_builder
      user:
        name: aur_builder
        group: wheel
    - name: Add permissions for aur_builder
      lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        mode: 0644
        create: true
        validate: 'visudo -cf %s'
  become: true

- name: Find out of date mirrorlist
  find:
    paths: [/etc/pacman.d]
    pattern: mirrorlist
    age: "{{ pkg_pacman_mirrorlist_age }}"
    age_stamp: mtime
  register: mirrorlist_found

- name: Update mirrorlist
  block:
    - name: Install reflector
      become: true
      pacman:
        name: reflector
        state: present
    - name: Create temp file for new mirrorlist
      tempfile:
        state: file
        suffix: pkg_mirrorlist
      register: mirrorlist_temp
    - name: Replace mirrorlist
      block:
        - name: Run reflector
          command:
            /usr/bin/python3 -m Reflector --verbose -p http -p https --latest 20 --sort rate --country "United States" --save {{ mirrorlist_temp.path }}
        - name: Backup mirrorlist
          become: true
          copy:
            src: /etc/pacman.d/mirrorlist
            dest: /etc/pacman.d/mirrorlist.bak
            mode: 0644
            force: true
        - name: Replace mirrorlist with new file
          become: true
          copy:
            src: "{{ mirrorlist_temp.path }}"
            dest: /etc/pacman.d/mirrorlist
            mode: 0644
      always:
        - name: Cleanup temp mirrorlist
          file:
            path: "{{ mirrorlist_temp.path }}"
            state: absent
      when: mirrorlist_temp is defined
  when: mirrorlist_found['matched'] or pkg_force_update_mirrorlist|d(false)

- name: Upgrade pacman packages
  become: true
  pacman:
    update_cache: true
    upgrade: true
  register: pacout

- name: Update aur packages
  command: yay -Su --aur --devel --noconfirm
  register: yayout
  changed_when: 'yayout.stdout is defined and "there is nothing to do" not in yayout.stdout'

# - name: Upgrade aur packages
#   become: true
#   become_user: aur_builder
#   yay:
#     update_cache: true
#     upgrade: true
