---
# arch hosts
- name: Create aur module user
  block:
    - name: Create user aur_builder
      user:
        name: aur_builder
        group: wheel
    - name: Add permissions for aur_builder
      lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: true
        validate: 'visudo -cf %s'
  become: true

- name: Find out age of mirrorlist
  find:
    paths: [/etc/pacman.d]
    pattern: mirrorlist
    age: "{{ pkg_pacman_mirrorlist_age }}"
    age_stamp: mtime
  register: mirrorlist_found

- name: Update mirrorlist
  block:
    - name: Install reflector
      become: true
      pacman:
        name: reflector
        state: present
    - name: Run reflector
      command: /usr/bin/python3 -m Reflector --verbose -p http -p https --latest 20 --sort rate --country "United States" --save {{ new_mirrorlist_path }}
    - name: Replace mirrorlist with new file
      become: true
      copy:
        src: "{{ pkg_pacman_new_mirrorlist_path }}"
        dest: /etc/pacman.d/mirrorlist
        backup: true
  when: mirrorlist_found['matched'] > 0

- name: Upgrade pacman packages
  become: true
  pacman:
    update_cache: true
    upgrade: true
  register: pacout

- name: Update aur packages
  become: true
  become_user: aur_builder
  command: yay -Syu --noconfirm
  register: yayout
  changed_when: 'yayout.stdout is defined and "there is nothing to do" not in yayout.stdout'
