---
# tasks for debian hosts
- name: Install default packages
  become: true
  apt:
    name: "{{ pkg_apt_packages }}"
    state: latest
    update_cache: true
  when:
    - pkg_apt_packages is defined
    - pkg_apt_packages|length
