---
# tasks/pip.yml
# - name: Check if pip3 installed
#   stat:
#     path: "{{ pkg_pip3_path }}"
#   register: pip3

# Failing will help debug system pip3 location
- name: Install/update python3 pip packages
  pip:
    name: "{{ pkg_python_packages }}"
    executable: "{{ pkg_pip3_path }}"
    extra_args: --user
    state: latest
