---
# neovim
- name: Clone Neovim git repo
  git:
    repo: https://github.com/neovim/neovim.git
    dest: "{{ neovim_source_dir }}"
    force: true
    accept_hostkey: true
  register: source_repo

- name: Build neovim from source
  block:
    - name: Install neovim build prerequisites
      become: true
      apt:
        name: "{{ Debian_neovim_required_packages }}"
        state: present
      when: ansible_facts['os_family'] == 'Debian'
    - name: Build and install neovim
      command: "{{ item }}"
      args:
        chdir: "{{ neovim_source_dir }}"
      loop:
        - make distclean
        - make CMAKE_BUILD_TYPE={{ neovim_cmake_build_type }}
        - make CMAKE_INSTALL_PREFIX={{ neovim_install_prefix }} install
  when: source_repo.before != source_repo.after or neovim_force_build
