---
# Install python dependencies
- name: Install neovim python dependencies
  apt:
    name: "{{ Debian_python_required_packages }}"
    state: "{{ install_state }}"
  become: yes

# Install neovim from ppa
- name: Install from ppa
  block:
    - name: Add neovim ppa
      apt_repository:
        repo: "{{ Debian_neovim_ppa }}"
        state: present
    - name: Install neovim from ppa
      apt:
        name: "{{ neovim_name }}"
        state: "{{ install_state }}"
  become: yes
  when: not ansible_facts['architecture'].startswith('arm')

- name: Install from source
  include_tasks: build.yml
  when: ansible_facts['architecture'].startswith('arm')
