---
# asdf defaults
asdf_git_repo: "https://github.com/asdf-vm/asdf.git"
asdf_version: "HEAD"
asdf_home: "{{ ansible_env.HOME }}"
asdf_dir: "{{ asdf_home }}/.asdf"

# shell config
# leave any shell blank to skip config
asdf_install_shell: /bin/sh
asdf_fish_config_dir: "{{ asdf_home }}/.config/fish"
asdf_nodejs_keyring: "{{ asdf_dir }}/keyrings/nodejs"

asdf_debian_packages:
  - build-essential
  - git
  - curl
  - libssl-dev
  - libbz2-dev
  - libsqlite3-dev
  - libreadline-dev
  - zlib1g-dev
  - wget
  - llvm
  - libncurses5-dev
  - xz-utils
  - tk-dev
  - libxml2-dev
  - libxmlsec1-dev
  - libffi-dev
asdf_osx_packages:
  - readline
  - xz
asdf_arch_packages:
  - base-devel
  - openssl
  - zlib
  - bzip2
  - readline
  - sqlite
  - wget
  - curl
  - llvm
  - ncurses
  - xz
  - tk
  - libffi
  - python-pyopenssl
  - git
