---
# tasks file for lua-language-server
- name: luals | Clone lua-language-server repo
  git:
    repo: https://github.com/sumneko/lua-language-server.git
    dest: "{{ source_dir }}"
    force: true
    recursive: true
  register: git_clone

- name: luals | Show commit hashes before/after pull
  debug:
    msg: |
      Before  {{ git_clone.before }}
      After   {{ git_clone.after }}
    verbosity: 1

- name: luals | Build and install lua-language-server
  block:
    - name: Run install script
      command: compile/install.sh
      args:
        chdir: "{{ source_dir }}/3rd/luamake"
      changed_when: true

    - name: Build server
      command: ./3rd/luamake/luamake rebuild
      args:
        chdir: "{{ source_dir }}"
      changed_when: true
  when: (git_clone.before != git_clone.after) or luals_force_build
