---
# tasks for pyenv

- name: Install platform-specific dependencies
  include_tasks: "{{ ansible_facts['os_family'] }}.yml"

- block:
  - name: Install user pyenv
    include_tasks: install.yml
    when: pyenv_env == "user"
  become: true
  become_user: "{{ pyenv_owner }}"

- block:
  - name: Install system pyenv
    include_tasks: install.yml
    when: pyenv_env == "system"
  become: true
