---
# vim
- name: Get python3 config dir
  command:
    argv:
      - /usr/bin/python3-config
      - --configdir
  register: python3_config_dir
  changed_when: false

- name: Clone vim master
  git:
    repo: https://github.com/vim/vim
    dest: "{{ vim_source_dir }}"
    depth: "1"
    force: true
  register: vim_git_clone

- name: Show commit hashes before/after pull
  debug:
    msg: |
      Before  {{ vim_git_clone.before }}
      After   {{ vim_git_clone.after }}
    verbosity: 1

- name: Build and install vim
  command: "{{ item }}"
  args:
    chdir: "{{ vim_source_dir }}"
  loop:
    - >
      ./configure \
          --prefix={{ install_path }}
          --with-features=huge
          --with-x=no
          --disable-gui
          --enable-multibyte
          --enable-cscope
          --enable-netbeans
          --enable-perlinterp
          --enable-python3interp
          --with-python3-config-dir={{ python3_config_dir.stdout }}
          --enable-rubyinterp
          --enable-luainterp
    - make -j{{ make_concurrency }}
    - make install
  when: (vim_git_clone.before != vim_git_clone.after) or vim_force_build
