---
# vim
- name: Get python3 config dir
  command:
    argv:
      - /usr/bin/python3-config
      - --configdir
  register: python3_config_dir
  changed_when: false

- name: Clone vim master
  git:
    repo: https://github.com/vim/vim
    dest: "{{ vim_source_dir }}"
    depth: "1"
    force: yes
  register: vim_git_clone

- name: Show message if git does not have changes
  debug:
    msg: No upstream vim changes! Skipping build.
  when: not vim_git_clone.changed

- name: Build and install vim
  command: "{{ item }}"
  args:
    chdir: "{{ vim_source_dir }}"
  loop:
    - >
      ./configure \
          --prefix={{ install_path }}
          --with-features=huge
          --with-x=yes
          --disable-gui
          --enable-multibyte
          --enable-cscope
          --enable-netbeans
          --enable-perlinterp
          --enable-python3interp
          --with-python3-config-dir={{ python3_config_dir.stdout }}
          --enable-rubyinterp
          --enable-luainterp
    - make -j{{ make_concurrency }}
    - make install
  when: vim_git_clone.changed or vim_force_build
