---
- name: Set flag to true if upgrade needed
  set_fact:
    vim_upgrade: True

- debug:
    msg: Forcing vim build/install
  when: vim_force_build and not vim_upgrade

- name: Install vim from source
  include_tasks: build.yml
  when: vim_upgrade or vim_force_build
