---
- name: Zoxide | Set arch string (Linux amd64)
  set_fact:
    zoxide_arch: x86_64-unknown-linux-musl
  when:
    - ansible_facts.system == 'Linux'
    - ansible_facts.architecture == 'x86_64'

- name: Zoxide | Set arch string (Linux arm32)
  set_fact:
    zoxide_arch: armv7-unknown-linux-gnueabihf
  when:
    - ansible_facts.system == 'Linux'
    - ansible_facts.architecture.startswith('arm')

- name: Zoxide | Set release url
  set_fact:
    zoxide_release_url:
      https://github.com/ajeetdsouza/zoxide/releases/download/{{ zoxide_latest_version }}/zoxide-{{ zoxide_latest_version }}-{{ zoxide_arch }}.tar.gz

- name: Zoxide | Download and install release
  block:
    - name: Zoxide | Create temp dl dir
      tempfile:
        state: directory
        suffix: _zoxide
      register: zoxide_dl_path

    - name: Zoxide | Get latest binary
      unarchive:
        src: "{{ zoxide_release_url }}"
        dest: "{{ zoxide_dl_path.path }}"
        remote_src: true

    - name: Zoxide | Set src path
      set_fact:
        zoxide_src_path: "{{ zoxide_dl_path.path }}"

    - name: Zoxide | Copy binary
      copy:
        src: "{{ zoxide_src_path }}/zoxide"
        dest: "{{ zoxide_prefix }}/bin/zoxide"
        mode: 0755

    - name: Zoxide | Copy man pages
      copy:
        src: "{{ zoxide_src_path }}/man/"
        dest: "{{ zoxide_prefix }}/share/man/man1"
        mode: 0644

    - name: Zoxide | Copy fish completions
      copy:
        src: "{{ zoxide_src_path }}/completions/zoxide.fish"
        dest: "{{ zoxide_home }}/.config/fish/completions"
        mode: 0644

    - name: Zoxide | Copy bash completions
      copy:
        src: "{{ zoxide_src_path }}/completions/zoxide.bash"
        dest: "{{ zoxide_home }}/.config/bash/completions"
        mode: 0644

    - name: Zoxide | Copy zsh completions
      copy:
        src: "{{ zoxide_src_path }}/completions/_zoxide"
        dest: "{{ zoxide_home }}/.config/zsh/completions"
        mode: 0644
  always:
    - name: Zoxide | Cleanup temp path
      file:
        path: "{{ zoxide_dl_path.path }}"
        state: absent
