# vim:ft=yaml.ansible:
---
- name: Ensure ssh setup
  hosts: all
  roles:
    - ssh

- name: Install asdf and plugins
  hosts: all
  roles:
    - asdf

- name: Install hub
  hosts: all
  roles:
    - hub
  strategy: linear

- name: Install software on all hosts
  hosts: all
  roles:
    - pkg
    - neovim
    - dotfiles

- name: Install vim
  hosts: jupiter
  roles:
    - vim
  tags:
    - vim

- name: Install rust
  hosts: all
  roles:
    - rust
  vars:
    - rust_version: 1.49
    - cargo_items:
      - name: cargo-update
        binary: cargo-install-update
      - name: ripgrep
        binary: rg
      - name: fd-find
        binary: fd
      - name: exa
      - name: lsd
      - name: sysinfo
        binary: sysinfo
        args: --git https://github.com/comfortablynick/sysinfo.git
      - name: just
      - name: bat
