---
# master level playbook
- import_playbook: asdf.yml
- import_playbook: fish.yml
- import_playbook: hub.yml
- import_playbook: luals.yml
- import_playbook: mosh.yml
- import_playbook: nvim.yml
- import_playbook: pipx.yml
- import_playbook: pkg.yml
- import_playbook: rust.yml
- import_playbook: ssh.yml
- import_playbook: tmux.yml
- import_playbook: vim.yml
