# vim:ft=yaml.ansible:
---
- name: Ensure ssh setup
  hosts: all
  roles:
    - ssh

- name: Install neovim
  hosts: all
  roles:
    - neovim
  tags:
    - nvim

- name: Sync dotfiles
  hosts: all
  roles:
    - dotfiles

- name: Install asdf and plugins
  hosts: all
  roles:
    - asdf

- name: Install hub
  hosts: all
  roles:
    - hub
  strategy: linear

- name: Install software on all hosts
  hosts: all
  roles:
    - pkg

- name: Install vim
  hosts: all
  roles:
    - vim
  tags:
    - vim

- name: Install tmux
  hosts: jupiter
  roles:
    - tmux
  tags:
    - tmux

- name: Install mosh
  hosts: pollux
  roles:
    - mosh
  tags:
    - mosh

- import_playbook: rust.yml
  tags:
    - rust

- name: Install pipx
  hosts: all
  roles:
    - role: pipx
      vars:
        pipx_pkgs: "{{ pipx_packages_all }} + {{ pipx_packages | default([]) }}"
  tags:
    - pipx
