---
version: 2
root-markers:
  - .git/
  - .projections.json
  - .tasks
  - .ansible-lint

tools:
  fish-shell: &fish-shell
    lint-command: 'fish -n'
    lint-ignore-exit-code: true
    lint-formats:
      - '%f (line %l): %m'

  fish-indent: &fish-indent
    format-command: 'fish_indent'
    format-stdin: true

  vim-vint: &vim-vint
    lint-command: 'vint --enable-neovim --stdin-display-name ${INPUT} -'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  make-checkmake: &make-checkmake
    lint-command: 'checkmake'
    lint-stdin: true

  markdown-markdownlint: &markdown-markdownlint
    lint-command: 'markdownlint -s -c %USERPROFILE%\.markdownlintrc'
    lint-stdin: true
    lint-formats:
      - '%f:%l %m'
      - '%f:%l:%c %m'
      - '%f: %l: %m'

  markdown-pandoc: &markdown-pandoc
    format-command: 'pandoc -f markdown -t gfm -sp --tab-stop=2'

  rst-pandoc: &rst-pandoc
    format-command: 'pandoc -f rst -t rst -s --columns=79'

  rst-lint: &rst-lint
    lint-command: 'rst-lint'
    lint-formats:
      - '%tNFO %f:%l %m'
      - '%tARNING %f:%l %m'
      - '%tRROR %f:%l %m'
      - '%tEVERE %f:%l %m'

  yaml-yamllint: &yaml-yamllint
    lint-command: 'yamllint -f parsable -'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: [%t%*[^ ]] %m'

  yaml-ansible-lint: &yaml-ansible-lint
    lint-command: 'ansible-lint --nocolor -qqp ${INPUT}'
    lint-ignore-exit-code: true
    lint-formats:
      - '%f:%l: %m'

  python-black: &python-black
    format-command: 'black --quiet -'
    format-stdin: true

  python-isort: &python-isort
    format-command: 'isort --stdout --profile black -'
    format-stdin: true

  python-flake8: &python-flake8
    lint-command: 'flake8 --stdin-display-name ${INPUT} -'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  python-mypy: &python-mypy
    lint-command: 'mypy --show-column-numbers'
    lint-ignore-exit-code: true
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -x -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  sh-shfmt: &sh-shfmt
    format-command: 'shfmt -ci -s -bn -i 4'
    format-stdin: true

  toml-taplo-lint: &toml-taplo-lint
    lint-command: 'taplo lint --silent -'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - '%-G'
      - '%-Gerror:\ aborting\ %.%#'
      - '%-Gerror:\ Could\ not\ compile\ %.%#'
      - '%Eerror:\ %m'
      - '%Eerror[E%n]:\ %m'
      - '%Wwarning:\ %m'
      - '%Inote:\ %m'
      - '%C\ %#-->\ %f:%l:%c'
      - '%E\ \ left:%m,%C\ right:%m\ %f:%l:%c,%Z'

  toml-taplo-fmt: &toml-taplo-fmt
    format-command: 'taplo format --silent -'
    format-stdin: true

  javascript-eslint: &javascript-eslint
    lint-command: 'eslint -f unix --stdin'
    lint-ignore-exit-code: true
    lint-stdin: true

  html-prettier: &html-prettier
    format-command: './node_modules/.bin/prettier --parser html'

  css-prettier: &css-prettier
    format-command: './node_modules/.bin/prettier --parser css'

  json-prettier: &json-prettier
    format-command: './node_modules/.bin/prettier --parser json'

  json-jq: &json-jq
    lint-command: 'jq .'

  json-fixjson: &json-fixjson
    format-command: 'fixjson'

  csv-csvlint: &csv-csvlint
    lint-command: 'csvlint'

  lua-lua-format: &lua-lua-format
    format-command: 'lua-format -i'
    format-stdin: true

  lua-stylua: &lua-stylua
    format-command: 'stylua -'
    format-stdin: true

  lua-luacheck: &lua-luacheck
    lint-command: 'luacheck --formatter=plain --codes --filename ${INPUT} -'
    lint-stdin: true
    lint-ignore-exit-code: true
    lint-formats:
      - '%f:%l:%c: (%t%*\d) %m'

languages:
  fish:
    - <<: *fish-shell
    - <<: *fish-indent

  vim:
    - <<: *vim-vint

  markdown:
    - <<: *markdown-markdownlint
    - <<: *markdown-pandoc

  rst:
    - <<: *rst-lint
    - <<: *rst-pandoc

  yaml:
    - <<: *yaml-yamllint

  yaml.ansible:
    - <<: *yaml-yamllint
    - <<: *yaml-ansible-lint

  toml:
    - <<: *toml-taplo-lint
    - <<: *toml-taplo-fmt

  python:
    - <<: *python-black
    - <<: *python-flake8
    - <<: *python-mypy
    - <<: *python-isort

  sh:
    - <<: *sh-shellcheck
    - <<: *sh-shfmt

  javascript:
    - <<: *javascript-eslint

  html:
    - <<: *html-prettier

  css:
    - <<: *css-prettier

  json:
    - <<: *json-jq
    - <<: *json-fixjson

  csv:
    - <<: *csv-csvlint

  lua:
    - <<: *lua-stylua
    - <<: *lua-luacheck
