---
# vim: ft=yaml.ansible:
# - import_playbook: asdf.yml

# - name: install base packages
#   hosts: all
#   roles:
#     - pkg-base
#     - neovim

- name: install tmux
  hosts:
    - mars
    - saturn
  roles:
    - tmux
