# vim:ft=yaml.ansible:
---
- name: Ensure ssh setup
  hosts: all
  roles:
    - ssh

- name: Install asdf and plugins
  hosts: all
  roles:
    - asdf

- name: Install hub
  hosts: all
  roles:
    - hub
  strategy: linear

- name: Install software on all hosts
  hosts: all
  roles:
    - pkg
    - neovim
    - dotfiles
