# vim:ft=yaml.ansible:
---
- name: Ensure ssh setup
  hosts: all
  roles:
    - ssh

- name: Install asdf and plugins
  hosts: all
  roles:
    - name: asdf
  environment:
    PYTHON_CONFIGURE_OPTS: "--enable-shared"

- name: Install software on all hosts
  hosts: all
  roles:
    # - pkg
    - neovim
    - tmux
    - dotfiles
