---
- name: Rust | Install cargo binaries
  command: "{{ cargo_bin }} install {{ item.name }} {{ item.args|d() }}"
  loop: "{{ cargo_packages }}"
  loop_control:
    label: "{{ item.name }}"
  register: cargo_result
  changed_when: "'use --force to override' not in cargo_result.stderr|d()"
  when: item.name is defined

- name: Rust | Verify binary installation
  stat:
    path: "{{ rust_user_dir }}/.cargo/bin/{{ item.binary|d(item.name) }}"
  loop: "{{ cargo_packages }}"
  loop_control:
    label: "{{ item.name }}"
  when: item is defined

- name: Rust | Download exa completions
  get_url:
    url: https://raw.githubusercontent.com/ogham/exa/master/completions/fish/exa.fish
    dest: "{{ ansible_facts.user_dir }}/.config/fish/completions/exa.fish"
  when: "cargo_packages | selectattr('name', 'equalto', 'exa')"
