---
- name: Rust | Check if rustup installed
  stat:
    path: '{{ rustup_bin }}'
  changed_when: false
  register: rustup_bin_stat

- name: Rust | Install rustup
  block:
    - name: Download rustup-init
      get_url:
        url: '{{ rustup_init_url }}'
        dest: /tmp/rustup-init
        mode: 0755
    - name: Install rust
      command: /tmp/rustup-init --no-modify-path -y --default-toolchain {{ rust_default_toolchain }}
      args:
        creates: '{{ rustup_home }}'
  always:
    - name: cleanup
      file:
        path: /tmp/rustup-init
        state: absent
  when: not rustup_bin_stat.stat.exists

- name: Rust | Rustup install toolchain
  command: "{{ rustup_bin }} toolchain install {{ item }}"
  register: rustup_toolchain_install
  changed_when: "'installed' in rustup_toolchain_install.stdout|d()"
  loop: "{{ rust_toolchains }}"
  when: item is defined


- name: Rust | Rustup update
  command: "{{ rustup_bin }} update"
  register: rust_rustup_update
  changed_when: "'updated' in rust_rustup_update.stdout|d()"
