---
# main tasks file for rust
- name: Rust | Include setup tasks
  include_tasks: setup.yml

- name: Rust | Install from installer
  include_tasks: installer.yml
  when:
    - not rust_build_from_source
    - not rust_stat_rustc is undefined

- name: Rust | Install from source
  include_tasks: source.yml
  when:
    - rust_build_from_source
    - not rust_stat_rustc.stat.exists

- name: Rust | Include tasks for Cargo
  include_tasks: cargo.yml
