---
# setup tasks file for rust
# - name: Rust | Formulate source string comparison requirements
#   set_fact:
#     key_value: ''
#     rust_version_requirement: "rustc {{ rust_version }}"
#   when:
#     - rust_build_from_source
#     - rust_version_requirement is undefined

# - name: Rust | Formulate installer string comparison requirements
#   set_fact:
#     key_value: ''
#     rust_version_requirement: "Usage: rustc"
#   when:
#     - not rust_build_from_source
#     - rust_version_requirement is not defined

# - name: Rust | Looking for installer installation
#   command: rustc
#   register: rust_preinstall_version_r
#   changed_when: false
#   failed_when: false
#   when: not rust_build_from_source

# - name: Rust | Looking for source installation
#   command: "{{ rust_user_dir }}/.cargo/bin/rustc --version"
#   register: rust_preinstall_version_s
#   changed_when: false
#   when: rust_build_from_source

- name: Rust | Detect if rustc is installed
  stat:
    path: "{{ rust_user_dir }}/.cargo/bin/rustc"
  register: rust_stat_rustc
  changed_when: false
