---
# rust source tasks
- name: Rust | Clone
  git:
    repo: https://github.com/rust-lang/rust.git
    dest: "{{ rust_source_dir }}"
    version: "{{ rust_version }}"
    clone: true
    force: true
  register: rust_clone
  changed_when: rust_clone.before != rust_clone.after

- name: Rust | Build and Install
  command:
    cmd: "{{ item }}"
    chdir: "{{ rust_source_dir }}"
  loop:
    - x.py build
    - x.py install cargo
  when: rust_clone.before != rust_clone.after
  changed_when: true

- name: Rust | Verify
  command: "{{ rust_user_dir }}/.cargo/bin/rustc --version"
  register: installed_rust_version
  changed_when: false
  failed_when: new_rust_version not in installed_rust_version.stdout
