---
# rust source tasks
- name: Rust | Clone
  git:
    repo: https://github.com/rust-lang/rust.git
    dest: "{{ rust_source_dir }}"
    version: "{{ rust_version }}"
    clone: true

- name: Rust | Build & Install
  command:
    - ./x.py build
    - ./x.py install cargo
  args:
    chdir: "{{ rust_source_dir }}"
  changed_when: false

- name: Rust | Verify
  command: "{{ rust_user_dir }}/.cargo/bin/rustc --version"
  register: installed_rust_version
  changed_when: false
  failed_when: new_rust_version not in installed_rust_version.stdout

