---
- name: lsd | Set arch string (Linux amd64)
  set_fact:
    lsd_arch: x86_64-unknown-linux-musl
  when:
    - ansible_facts.system == 'Linux'
    - ansible_facts.architecture == 'x86_64'

- name: lsd | Set arch string (Linux arm32)
  set_fact:
    lsd_arch: arm-unknown-linux-gnueabihf
  when:
    - ansible_facts.system == 'Linux'
    - ansible_facts.architecture.startswith('arm')

- name: lsd | Set release filename
  set_fact:
    lsd_filename: lsd-v{{ lsd_latest_version }}-{{ lsd_arch }}
    lsd_suffix: tar.gz

- name: lsd | Set release url
  set_fact:
    lsd_release_url: https://github.com/lsd-rs/lsd/releases/download/v{{ lsd_latest_version }}/{{ lsd_filename }}.{{ lsd_suffix }}

- name: lsd | Create temp dl dir
  tempfile:
    state: directory
    suffix: _lsd
  register: lsd_dl_dir

- name: lsd | Set downloaded folder path
  set_fact:
    lsd_dl_path: "{{ lsd_dl_dir.path }}/{{ lsd_filename }}"

- name: lsd | Get latest binary
  unarchive:
    src: "{{ lsd_release_url }}"
    dest: "{{ lsd_dl_dir.path }}"
    remote_src: true
    creates: "{{ lsd_dl_path }}"
