---
# tasks file for lsd
- name: Lsd | Get latest release
  uri:
    url: https://api.github.com/repos/Peltoche/lsd/releases/latest
    return_content: true
  run_once: false
  register: lsd_latest
  changed_when: false

- name: Lsd | Get installed version
  command: "lsd --version"
  register: lsd_installed
  changed_when: false
  failed_when: false

- name: Lsd | Set version strings
  set_fact:
    lsd_installed_version: "{% if lsd_installed.stdout is defined %}{{ lsd_installed.stdout.split(' ')[1] }}{% else %} none {% endif %}"
    lsd_latest_version: "{{ lsd_latest.json.tag_name }}"
    lsd_releases: "{{ lsd_latest.json.assets }}"
  changed_when: false

- name: Lsd | Debug versions
  debug:
    msg: |
      lsd installed vesion: {{ lsd_installed_version }}
      lsd latest version:   {{ lsd_latest_version }}
    verbosity: 1

- name: Lsd | Include download tasks
  block:
    - include_tasks: download.yml
    - include_tasks: install.yml
  always:
    - name: Lsd | Clean up downloaded files
      file:
        path: "{{ lsd_dl_dir.path }}"
        state: absent
      when: lsd_dl_dir.path is defined
  when: lsd_installed.rc != 0 or (lsd_latest_version is version(lsd_installed_version, '>')) or lsd_force|d(false)
