---
# tasks file for lsd
- name: Lsd | Get latest release
  uri:
    url: https://api.github.com/repos/Peltoche/lsd/releases/latest
    return_content: true
  run_once: false
  register: lsd_latest
  changed_when: false

- name: Lsd | Get installed version
  command: "lsd --version"
  register: lsd_installed_version
  changed_when: false
  failed_when: false

- name: Lsd | Set version strings
  set_fact:
    key_value: ''
    lsd_installed_version: "{{ lsd_installed_version.stdout.split(' ')[1] }}"
    lsd_latest_version: "{{ lsd_latest.json.tag_name }}"
    lsd_releases: "{{ lsd_latest.json.assets }}"
  changed_when: false
  when: lsd_installed_version is defined

- name: Lsd | Debug versions
  debug:
    msg: |
      lsd installed vesion: {{ lsd_installed_version|d() }}
      lsd latest version:   {{ lsd_latest_version|d() }}
    verbosity: 1

- name: Lsd | Include download tasks
  block:
    - include_tasks: download.yml
    - include_tasks: install.yml
  always:
    - name: Lsd | Clean up downloaded files
      file:
        path: "{{ lsd_dl_dir.path }}"
        state: absent
      when: lsd_dl_dir.path is defined
  when: lsd_latest_version|d(0) is version(lsd_installed_version|d(0), '>') or lsd_force|d(false)
