---
# tasks file for pipx
- name: Install pipx
  pip:
    name: pipx
    executable: "{{ pipx_pip3_path }}"
    state: latest

- name: Get installed pipx packages
  command: "{{ pipx_path }} list"
  register: pipx_installed
  changed_when: false

- name: Debug packages
  debug:
    var: pipx_pkgs

- name: Debug $PIPX_BIN_DIR
  debug:
    var: ansible_env.PIPX_BIN_DIR
    verbosity: 1

- name: Install pipx packages
  command: "{{ pipx_path }} install {{ item.name }}"
  loop: "{{ pipx_pkgs }}"
  register: pipx
  changed_when: "'--force' not in pipx.stdout"
  when:
    - pipx_installed.stdout is defined
    - item.name not in pipx_installed.stdout

- name: Inject pipx dependencies
  command: "{{ pipx_path }} inject {{ item.name }} {{ item.inject|join(' ') }}"
  loop: "{{ pipx_pkgs }}"
  when: item.inject is defined
  changed_when: false  # no way to detect if this is a change or not
