---
# tasks file for pipx
- name: Check for line in .tool-versions
  command: grep -i 'python 3' {{ ansible_facts.user_dir }}/.tool-versions
  register: asdf_python_version
  changed_when: false

- name: Set python dir
  set_fact:
    asdf_python_bin_dir: "{{ asdf_dir }}/installs/python/{{ asdf_python_version.stdout|replace('python ', '') }}/bin"
  when: asdf_python_version.stdout is defined

- name: Set python paths
  set_fact:
    pipx_pip3_path: "{{ asdf_python_bin_dir }}/pip3"
    pipx_path: "{{ asdf_python_bin_dir }}/pipx"
  when: asdf_python_bin_dir is defined

- name: Install pipx
  pip:
    name: pipx
    executable: "{{ pipx_pip3_path }}"
    state: latest
  register: pip
  changed_when: "'Successfully installed' in pip.stdout|default('')"

- name: Debug packages
  debug:
    var: pipx_pkgs
    verbosity: 1

- name: Install pipx packages
  community.general.pipx:
    name: "{{ item.name }}"
    source: "{{ item.source|d(omit) }}"
    state: install
    executable: "{{ pipx_path }}"
  loop: "{{ pipx_pkgs }}"

- name: Inject pipx dependencies
  community.general.pipx:
    name: "{{ item.name }}"
    source: "{{ item.source|d(omit) }}"
    state: inject
    inject_packages: "{{ item.inject }}"
    executable: "{{ pipx_path }}"
  loop: "{{ pipx_pkgs }}"
  when: item.inject is defined

- name: Inject pipx dependencies
  community.general.pipx:
    state: upgrade_all
    executable: "{{ pipx_path }}"
