---
# tasks file for mosh
- name: Mosh | Build from source
  include_tasks: build.yml
  when: ansible_facts.system == 'Linux'

- name: Mosh | Install from homebrew
  include_tasks: install.yml
  when: ansible_facts.system == 'Darwin'
