---
# dotfiles
- name: Link files
  block:
    - name: Attempt link
      file:
        src: "{{ base_dir }}/{{ item.value['src'] }}"
        dest: "{{ item.value['dst'] }}"
        state: link
        force: yes
  rescue:
    - debug:
        msg: "Recovering from error on {{ item.key }}"
    - name: Check current file
      stat:
        path: "{{ item.value['dst'] }}"
      register: errfile
    - debug:
        msg: "File causing error: {{ errfile.stat|to_nice_json }}"
        verbosity: 1
    - name: Remove and replace existing directory
      block:
      - name: Remove existing directory
        file:
          path: "{{ item.value['dst'] }}"
          state: absent
      - name: Retry linking directory
        file:
          src: "{{ base_dir }}/{{ item.value['src'] }}"
          dest: "{{ item.value['dst'] }}"
          state: link
      when: errfile.stat.isdir is defined and errfile.stat.isdir
