---
# arch hosts
- name: Create aur module user
  block:
    - name: Create user aur_builder
      user:
        name: aur_builder
        group: wheel
    - name: Add permissions for aur_builder
      lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: yes
        validate: 'visudo -cf %s'
  become: yes

- name: Upgrade pacman packages
  become: true
  pacman:
    update_cache: yes
    upgrade: yes

- name: Update aur packages
  become: yes
  become_user: aur_builder
  aur:
    upgrade: yes
    use: yay
    aur_only: yes
