---
# arch hosts
- name: Create aur module user
  block:
    - name: Create user aur_builder
      user:
        name: aur_builder
        group: wheel
    - name: Add permissions for aur_builder
      lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: yes
        validate: 'visudo -cf %s'
  become: yes

- name: Find out age of mirrorlist
  find:
    paths: /etc/pacman.d
    pattern: mirrorlist
    age: "{{ mirrorlist_file_age }}"
    age_stamp: mtime
  register: mirrorlist_found

- name: Update mirrorlist
  block:
    - name: Install reflector
      pacman:
        name: reflector
        state: present
    - name: Run reflector
      command: /usr/bin/python3 -m Reflector --verbose -p http -p https --latest 20 --sort rate --country "United States" --save {{ new_mirrorlist_path }}
    - name: Replace mirrorlist with new file
      copy:
        src: "{{ new_mirrorlist_path }}"
        dest: /etc/pacman.d/mirrorlist
        backup: yes
  become: yes
  when: mirrorlist_found['matched'] > 0

- name: Upgrade pacman packages
  become: yes
  pacman:
    update_cache: yes
    upgrade: yes

- name: Update aur packages
  become: yes
  become_user: aur_builder
  command: yay -Syu --noconfirm
  register: yayout
  changed_when: '"there is nothing to do" not in yayout.stdout'

  # aur:
  #   upgrade: yes
  #   use: auto
  #   aur_only: yes
