---
# tasks file for pkg
- name: Handle os-specific packages
  include_tasks: "{{ ansible_facts['os_family'] }}.yml"

- name: Check if pip2 installed
  stat:
    path: /usr/bin/pip2
  register: pip2_st

- name: Check if pip3 installed
  stat:
    path: "{{ pip3_path }}"
  register: pip3_st

- name: Install/update python2 pip packages
  pip:
    name:
      - virtualenv
      - pip
    executable: pip2
    state: latest
  when: pip2_st.exists is defined and pip2_st.exists

- name: Install/update python3 pip packages
  pip:
    name: "{{ pip3_default_pkgs }}"
    executable: "{{ pip3_path }}"
    state: latest
  when: pip3_st.exists is defined and pip3_st.exists

- name: asdf reshim
  command: "{{ asdf_bin }} reshim"

- name: Install/update pipx packages
  include_tasks: pipx.yml
