---
- name: Install pipx
  pip:
    name: pipx
    executable: "{{ pip3_path }}"
    state: latest

- name: Get installed pipx packages
  command: "{{ pipx_path }} list"
  register: pipx_installed
  changed_when: false

- name: Install pipx packages
  command: "{{ pipx_path }} install {{ item }}"
  loop: "{{ pipx_default_pkgs }}"
  register: pipx
  changed_when: "'--force' not in pipx.stdout"
  environment:
    - PIPX_BIN_DIR: "{{ pipx_bin_dir }}"
  when:
    - pipx_installed.stdout is defined
    - item not in pipx_installed.stdout

- name: Inject pipx dependencies
  command: "{{ pipx_path }} inject {{ item.pkg }} {{ item.inject }}"
  loop: "{{ pipx_inject_dependencies }}"
  changed_when: false # there seems to be no way to detect if this is a change or not
