---
# tasks file for fish_shell
- name: Fish shell | Clone git repo
  git:
    repo: https://github.com/fish-shell/fish-shell
    dest: "{{ fish_source_dir }}"
    force: true
    accept_hostkey: true
  register: source_repo

- name: Fish shell | Get installed version
  command: "{{ fish_install_prefix }}/bin/fish --version"
  register: fish_installed_version
  changed_when: false

- name: Fish shell | Debug missing install
  debug:
    msg: Current fish install not found at '{{ fish_install_prefix }}/bin/fish'!
  when: fish_installed_version.rc != 0

- name: Fish shell | Set version strings
  set_fact:
    fish_installed_sha: "{% if fish_installed_version.stdout|length > 1 %}{{ fish_installed_version.stdout[-9:] }}{% else %}0{% endif %}"
    fish_master_sha: "{{ source_repo.after[:9] }}"

- name: Fish shell | Build from git master
  block:
    - name: Remove existing build dir if exists
      file:
        path: "{{ fish_source_dir }}/build"
        state: absent

    - name: Make build dir
      file:
        path: "{{ fish_source_dir }}/build"
        state: directory
        mode: 0755

    - name: Build fish
      command: "{{ item }}"
      args:
        chdir: "{{ fish_source_dir }}/build"
      loop:
        - cmake -DCMAKE_INSTALL_PREFIX={{ fish_install_prefix }} ..
        - make
      changed_when: true

    - name: Install fish
      command: make install
      args:
        chdir: "{{ fish_source_dir }}/build"
      become: true
      changed_when: true
  when: (fish_installed_sha != fish_master_sha) or fish_force_build
