---
# defaults file for neovim

# The specific package name used to install neovim
neovim_name: neovim

# Debian
Debian_neovim_ppa: ppa:neovim-ppa/unstable
Debian_python_required_packages:
    - software-properties-common
    - python-dev
    - python-pip
    - python3-dev
    - python3-pip
Debian_neovim_required_packages:
    - gperf
    - libluajit-5.1-dev
    - libunibilium-dev
    - libmsgpack-dev
    - libtermkey-dev
    - libvterm-dev
    - libjemalloc-dev
    - lua5.1
    - lua-lpeg
    - lua-mpack
    - lua-bitop
    - libuv1-dev
    - lua-luv-dev

# Whether or not to install or remove neovim
# choices: [ present, absent, latest ]
install_state: latest

# Whether or not to configure or remove configuration
# choices: [ present, absent ]
configure_state: present

nvim_venv_dir: "{{ ansible_env.HOME }}/.env"
nvim_py2_venv_name: nvim2
nvim_py3_venv_name: nvim3
pip2_name: pip2
pip3_name: pip3

# Build from source
neovim_source_dir: "{{ ansible_env.HOME }}/src/neovim"
neovim_cmake_build_type: Release
neovim_install_prefix: "{{ ansible_env.HOME }}/.local"
neovim_force_build: false
