---
# defaults file for neovim

# Debian
Debian_neovim_ppa: ppa:neovim-ppa/unstable
Debian_python_required_packages:
    - software-properties-common
    - python-dev
    - python-pip
    - python3-dev
    - python3-pip
Debian_neovim_required_packages:
    - gperf
    - libluajit-5.1-dev
    - libunibilium-dev
    - libmsgpack-dev
    - libtermkey-dev
    - libvterm-dev
    - libjemalloc-dev
    - lua5.1
    - lua-lpeg
    - lua-mpack
    - lua-bitop
    - libuv1-dev
    - lua-luv-dev

# Build from source
neovim_home: "{{ ansible_facts.user_dir }}"
neovim_source_dir: "{{ neovim_home }}/src/neovim"
neovim_cmake_build_type: Release
neovim_install_prefix: "{{ neovim_home }}/.local"
neovim_force: false
neovim_build: false
neovim_keep_theme_files:
    - default.vim
    - murphy.vim
