---
# defaults file for pkg
pkg_apt_packages: []

pkg_pacman_packages: []

pkg_aur_packages: []

# system python3 packages
pkg_python_packages: []

pkg_pip3_path: /usr/bin/pip3

pkg_pacman_mirrorlist_age: "1w"
