---
# defaults file for pyenv
pyenv_env: "user"
pyenv_path: "{% if pyenv_env == 'user' %}{{ ansible_env.HOME }}/pyenv{% else %}/usr/local/pyenv{% endif %}"
pyenv_owner: "{{ ansible_env.USER }}"
pyenv_setting_path: "{% if pyenv_env == 'user' %}~/.bashrc{% else %}/etc/profile.d/pyenv.sh{% endif %}"
pyenv_update_git_install: no
pyenv_enable_autocompletion: no
pyenv_python_versions:
  - 3.7.4
pyenv_virtualenvs:
  - { venv_name: "latest", py_version: "3.7.4" }
# For a system install, the shims dir will not be writable by users, disable rehashing
pyenv_init_options: "{% if pyenv_env != 'user' %}--no-rehash{% endif %}"

pyenv_update: no

# additional options for the build process, e.g "--enable-shared"
pyenv_python_configure_opts: "--enable-shared"

pyenv_debian_packages:
  - build-essential
  - git
  - curl
  - libssl-dev
  - libbz2-dev
  - libsqlite3-dev
  - libreadline-dev
  - zlib1g-dev
  - wget
  - llvm
  - libncurses5-dev
  - xz-utils
  - tk-dev
  - libxml2-dev
  - libxmlsec1-dev
  - libffi-dev
pyenv_osx_packages:
  - readline
  - xz
