---
# tasks file for pkg-base
- name: Handle os packages
  include_tasks: "{{ ansible_facts['os_family'] }}.yml"

- block:
  - name: Install/update python2 pip packages
    pip:
      name:
        - virtualenv
        - pip
      executable: ~/.asdf/shims/pip2
      state: latest
  - name: Install/update python3 pip packages
    pip:
      name: "{{ pip3_default_pkgs }}"
      executable: ~/.asdf/shims/pip3
      state: latest
  - name: Make asdf binaries available
    shell: . {{ asdf_dir }}/asdf.sh && asdf reshim

- name: Install pipx packages
  shell: "{{ asdf_dir }}/shims/pipx install {{ item }}"
  loop: "{{ pipx_default_pkgs }}"
  environment:
    - PIPX_BIN_DIR: "{{ pipx_bin_dir }}"
