---
# neovim
- name: Clone Neovim git repo
  git: https://github.com/neovim/neovim.git
  dest: "{{ neovim_source_dir }}"
  force: yes
  accept_hostkey: yes
  register: source_repo

- block:
  - name: Install build prerequisites
    become: yes
    apt:
      name: "{{ Debian_neovim_required_packages }}"
      state: present
    when: "{{ ansible_facts['os_family'] }} == 'Debian'"
  - name: Build from source_repo
    command: make CMAKE_BUILD_TYPE="{{ neovim_cmake_build_type }}"
    chdir: "{{ neovim_source_dir }}"
  when: source_repo.changed
