format = "$all"
add_newline = true
scan_timeout = 10

[hostname]
disabled = true

[username]
disabled = true

[directory]
style = "39"
truncate_to_repo = false
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = ""
style = "14"
format = "[$symbol $branch]($style) "

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
modified = "Δ${count}"
staged = "●"
conflicted = "‼"
style = "9"
format = "[$all_status]($style) "

[cmd_duration]
style = "243"
min_time = 0
show_milliseconds = true
format = "[$duration]($style)"

# [nodejs]
# disabled = true
