---
# defaults file for rust
rustup_init_url: https://sh.rustup.rs
rust_user_dir: "{{ ansible_facts.user_dir }}"
rust_cargo_dir: "{{ rust_user_dir }}/.cargo"
rust_cargo_tmp_dir: "{{ rust_cargo_dir }}/tmp"
rustup_bin: "{{ rust_cargo_dir }}/bin/rustup"
cargo_bin: "{{ rust_cargo_dir }}/bin/cargo"

rust_build_from_source: false
rust_source_dir: "{{ rust_user_dir }}/src/rust"

rust_toolchains:
  - stable

rust_default_toolchain: stable
