---
# defaults file for rust
rust_user_dir: "{{ ansible_env.HOME }}"
rustup_path: "{{ rust_user_dir }}/.cargo/bin/rustup"
cargo_bin: "{{ rust_user_dir }}/.cargo/bin/cargo"
rust_update: 2020-08-12 09:45:06 CDT
rust_install_clean: false

rust_build_from_source: false
rust_source_dir: "{{ ansible_env.HOME }}/src/rust"

rust_toolchains:
  - stable

rust_default_toolchain: stable
