# vim: set fdm=marker:
# Vim-Only Plugins
# Status bar {{{
[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = '/usr/local/lib/python3.7/site-packages/powerline/bindings/vim'
on_if = 1
lazy = 1

[[plugins]]
repo = 'maximbaz/lightline-ale'
# }}}
# Code completion {{{
[[plugins]]
repo = 'Valloric/YouCompleteMe'
build = './install.py --ts-completer --clang-completer'
on_ft = ['python', 'javascript', 'typescript', 'cpp', 'c']
hook_source = '''
let g:ycm_filetype_blacklist = {
    \ 'gitcommit': 1,
    \ 'tagbar': 1,
    \ 'qf': 1,
    \ 'notes': 1,
    \ 'markdown': 1,
    \ 'unite': 1,
    \ 'text': 1,
    \ 'vimwiki': 1,
    \ 'pandoc': 1,
    \ 'infolog': 1,
    \ 'mail': 1
    \}
let g:ycm_filetype_specific_completion_to_disable = {
    \ 'gitcommit': 1
    \}
let g:ycm_autoclose_preview_window_after_completion = 1
'''
# }}}
