# vim: set fdm=marker:
# Code completion {{{
[[plugins]]
repo = 'Shougo/deoplete.nvim'
# build = 'nvim -s +"call dein#remote_plugins()"'
build = 'nvim -c "call dein#remote_plugins()"'
on_event = 'InsertEnter'
hook_source = '''
call deoplete#enable()
let g:deoplete#sources#jedi#show_docstring = 1
inoremap <expr><tab> pumvisible() ? "\<c-n>" : "\<tab>"
autocmd InsertLeave,CompleteDone * if pumvisible() == 0 | pclose | endif
'''

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'

[[plugins]]
repo = 'mhartington/nvim-typescript'
build = './install.sh'
on_ft = ['typescript', 'tsx']
# }}}
# Status bar {{{
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_source = '''
let g:airline_extensions = [
    \ 'tabline',
    \ 'ale',
    \ 'branch',
    \ 'hunks',
    \ 'wordcount',
    \ 'virtualenv'
    \ ]
let g:airline#extensions#default#section_truncate_width = {
    \ 'b': 79,
    \ 'x': 40,
    \ 'y': 48,
    \ 'z': 45,
    \ 'warning': 80,
    \ 'error': 80,
    \ }
let g:airline_powerline_fonts = 1
let g:airline_detect_spelllang = 0
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
on_if = 'has("nvim")'
# }}}
