---
# tasks file for env
- name: Env | Debug path vars
  ansible.builtin.debug:
    var: env_paths
    verbosity: 1

- name: Env | Debug env vars
  ansible.builtin.debug:
    var: env_vars
    verbosity: 1

- name: Env | Create bash file from template
  template:
    src: posix.j2
    dest: "{{ env_bash_env_file }}"
    mode: "644"
  vars:
    shell: bash

- name: Env | Create zsh file from template
  template:
    src: posix.j2
    dest: "{{ env_zsh_env_file }}"
    mode: "644"
  vars:
    shell: zsh

- name: Env | Create fish file from template
  template:
    src: fish.j2
    dest: "{{ env_fish_env_file }}"
    mode: "644"
