---
# asdf defaults
asdf_git_repo: "https://github.com/asdf-vm/asdf.git"
asdf_version: "v0.7.3"
asdf_home: "{{ ansible_env.HOME }}"
asdf_dir: "{{ asdf_home }}/.asdf"

# shell config
# leave any shell blank to skip config
asdf_install_shell: /bin/bash
asdf_bashrc_path: "{{ asdf_home }}/.bashrc"
asdf_zshrc_path: "{{ asdf_home }}/.zshrc"
asdf_fish_config_path: "{{ asdf_home }}/.config/fish/config.fish"

# plugins
asdf_plugins:
  - name: python
    versions:
      - "3.7.4"
      - "2.7.16"
    global: "3.7.4 2.7.16"

asdf_debian_packages:
  - build-essential
  - git
  - curl
  - libssl-dev
  - libbz2-dev
  - libsqlite3-dev
  - libreadline-dev
  - zlib1g-dev
  - wget
  - llvm
  - libncurses5-dev
  - xz-utils
  - tk-dev
  - libxml2-dev
  - libxmlsec1-dev
  - libffi-dev
asdf_osx_packages:
  - readline
  - xz
asdf_arch_packages:
  - base-devel
  - openssl
  - zlib
  - bzip2
  - readline
  - sqlite
  - wget
  - curl
  - llvm
  - ncurses
  - xz
  - tk
  - libffi
  - python-pyopenssl
  - git
